export type BeachLang = {
  type: string;
  access: string;
  tips: string;
  desc: string;
  crowd: string;
  food: string;
  seabed: string;
  parking_info: string;
};

export type Beach = {
  id: string;
  name: string;
  location: string;
  prov: "PA" | "TP";
  lat: number;
  lng: number;
  time: string;
  dist: string;
  kids: boolean;
  lidi: boolean;
  snorkel: boolean;
  park: boolean;
  parking_type: "free" | "paid" | "mixed";
  wind_bad: string[];
  wind_good: string[];
  it: BeachLang;
  en: BeachLang;
};

export const beaches: Beach[] = [
  { id: "cala-muletti", name: "Cala Muletti", location: "Terrasini", prov: "PA", lat: 38.095, lng: 13.055, time: "12 min", dist: "7 km", kids: false, lidi: false, snorkel: true, park: false, parking_type: "free", wind_bad: ["Maestrale", "Tramontana", "Ponente"], wind_good: ["Scirocco", "Ostro", "Levante"], it: { type: "Scogli/Grotta", access: "Scalinata", tips: "Lungo i gradini c'è un bunker della 2° Guerra Mondiale.", desc: "Molto virale per la spettacolare scalinata panoramica a strapiombo sul mare.", crowd: "Media (Alta nei weekend)", food: "Nessun servizio, portare acqua", seabed: "Subito profondo tra gli scogli", parking_info: "Gratuito su strada o nello spiazzo panoramico in terra battuta (posti limitati)." }, en: { type: "Rocks/Cave", access: "Stairs", tips: "There is a WWII bunker along the steps.", desc: "Very viral for its spectacular panoramic staircase overhanging the sea.", crowd: "Medium (High on weekends)", food: "No services, bring water", seabed: "Deep immediately among rocks", parking_info: "Free street or cliffside dirt turnout parking (limited spots)." } },
  { id: "san-cataldo", name: "San Cataldo", location: "Trappeto/Terrasini", prov: "PA", lat: 38.086, lng: 13.045, time: "10 min", dist: "5 km", kids: false, lidi: false, snorkel: true, park: false, parking_type: "free", wind_bad: ["Maestrale", "Tramontana", "Grecale"], wind_good: ["Scirocco", "Ostro", "Libeccio"], it: { type: "Ciottoli/Scogli", access: "Sterrato", tips: "Natura selvaggia, porta scarpette da scoglio.", desc: "Baia incontaminata vicinissima, ideale per sfuggire alla folla.", crowd: "Tranquilla/Bassa", food: "Nessun chiosco, 100% selvaggia", seabed: "Ciottoli, scende rapidamente", parking_info: "Gratuito nello spiazzo sterrato adiacente all'accesso della baia." }, en: { type: "Pebbles/Rocks", access: "Dirt road", tips: "Wild nature, bring water shoes.", desc: "Pristine bay very close, ideal to escape the crowds.", crowd: "Quiet/Low", food: "No kiosks, 100% wild", seabed: "Pebbles, drops quickly", parking_info: "Free dirt parking area right next to the path entrance." } },
  { id: "cala-rossa-terrasini", name: "Cala Rossa", location: "Terrasini", prov: "PA", lat: 38.151, lng: 13.072, time: "20 min", dist: "18 km", kids: false, lidi: false, snorkel: true, park: true, parking_type: "free", wind_bad: ["Maestrale", "Tramontana", "Ponente"], wind_good: ["Scirocco", "Levante", "Ostro"], it: { type: "Scogli/Rocce", access: "Facile", tips: "Vieni qui al tramonto per foto spettacolari.", desc: "Scogliere di roccia rossa con venature bianche a picco sul mare.", crowd: "Media", food: "Bar e chioschi nelle vicinanze", seabed: "Profondo, ideale per tuffi/snorkeling", parking_info: "Gratuito lungo la strada panoramica e piazzali vicini alla torre." }, en: { type: "Rocks", access: "Easy", tips: "Come here at sunset for spectacular photos.", desc: "Red rock cliffs with white veins overlooking the sea.", crowd: "Medium", food: "Bars and kiosks nearby", seabed: "Deep, ideal for diving/snorkeling", parking_info: "Free parking along the coastal road and near the tower." } },
  { id: "aspra", name: "Aspra", location: "Bagheria", prov: "PA", lat: 38.106, lng: 13.504, time: "55 min", dist: "55 km", kids: true, lidi: false, snorkel: false, park: true, parking_type: "mixed", wind_bad: ["Tramontana", "Grecale", "Maestrale"], wind_good: ["Scirocco", "Libeccio", "Ostro"], it: { type: "Sabbia chiara", access: "Facile", tips: "Mangia un gelato nel borgo marinaro dopo il mare.", desc: "Spiaggetta autentica tra le barche colorate dei pescatori.", crowd: "Alta nei weekend", food: "Ristoranti e gelaterie sul lungomare", seabed: "Sabbioso e digradante", parking_info: "Misto: strisce blu a pagamento sul lungomare e posti liberi nelle vie interne." }, en: { type: "Light sand", access: "Easy", tips: "Have an ice cream in the fishing village after.", desc: "Authentic small beach among colorful fishing boats.", crowd: "High on weekends", food: "Restaurants and ice cream shops on promenade", seabed: "Sandy and sloping", parking_info: "Mixed: paid blue lines on seafront and free spots in side streets." } },
  { id: "sant-elia", name: "Caletta di Sant'Elia", location: "Santa Flavia", prov: "PA", lat: 38.089, lng: 13.535, time: "1h", dist: "58 km", kids: false, lidi: false, snorkel: true, park: false, parking_type: "paid", wind_bad: ["Tramontana", "Grecale"], wind_good: ["Scirocco", "Libeccio", "Ostro"], it: { type: "Scogli", access: "Scalinata", tips: "Una delle calette più fotografate di Sicilia.", desc: "Un'insenatura romantica incastrata tra le case e il mare.", crowd: "Molto Alta", food: "Locali nel borghetto adiacente", seabed: "Profondo, cristallino", parking_info: "A pagamento (strisce blu nel borgo marinaro). Posti ridotti." }, en: { type: "Rocks", access: "Stairs", tips: "One of the most photographed coves in Sicily.", desc: "A romantic inlet wedged between houses and the sea.", crowd: "Very High", food: "Places in the adjacent hamlet", seabed: "Deep, crystal clear", parking_info: "Paid blue lines in the village. Very limited capacity." } },
  { id: "salinelle", name: "Salinelle", location: "Lascari", prov: "PA", lat: 38.021, lng: 13.935, time: "1h 15 min", dist: "100 km", kids: true, lidi: true, snorkel: false, park: true, parking_type: "free", wind_bad: ["Tramontana", "Grecale", "Maestrale"], wind_good: ["Scirocco", "Ostro", "Libeccio"], it: { type: "Sabbia dorata", access: "Facile", tips: "Alternativa perfetta se Cefalù è troppo caotica.", desc: "Chilometri di spiaggia sabbiosa con tanto spazio.", crowd: "Media (Spazi molto ampi)", food: "Lidi attrezzati e chioschi", seabed: "Sabbioso, scende gradualmente", parking_info: "Gratuito e facilissimo negli ampi spazi dietro le dune e lungo la spiaggia." }, en: { type: "Golden sand", access: "Easy", tips: "Perfect alternative if Cefalù is too chaotic.", desc: "Kilometers of sandy beach with plenty of space.", crowd: "Medium (Very wide spaces)", food: "Equipped beach clubs and kiosks", seabed: "Sandy, drops gradually", parking_info: "Free and very easy parking in large open areas behind the beach." } },
  { id: "san-teodoro", name: "San Teodoro (Stagnone)", location: "Marsala", prov: "TP", lat: 37.848, lng: 12.441, time: "1h", dist: "75 km", kids: true, lidi: true, snorkel: false, park: true, parking_type: "paid", wind_bad: ["Libeccio", "Ponente", "Scirocco"], wind_good: ["Tramontana", "Grecale", "Levante"], it: { type: "Sabbia/Fondale basso", access: "Facile", tips: "Tramonto epico sulle saline. Acqua caldissima.", desc: "Acqua alle caviglie, potresti camminare fino all'isola di fronte!", crowd: "Alta al tramonto", food: "Lido ristorante/aperitivi in loco", seabed: "Bassissimo (alla caviglia per km)", parking_info: "Parcheggio gestito a pagamento vicinissimo all'accesso." }, en: { type: "Sand/Shallow", access: "Easy", tips: "Epic sunset over salt pans. Very warm water.", desc: "Ankle-deep water, you could walk to the island opposite!", crowd: "High at sunset", food: "Beach club/restaurant on site", seabed: "Very shallow (ankle deep for km)", parking_info: "Paid managed parking lot right at beach access." } },
  { id: "trabia", name: "Trabia (Spiaggia Vetrana)", location: "Trabia", prov: "PA", lat: 37.997, lng: 13.655, time: "1h", dist: "75 km", kids: true, lidi: true, snorkel: false, park: true, parking_type: "mixed", wind_bad: ["Maestrale", "Tramontana", "Grecale"], wind_good: ["Scirocco", "Ostro", "Libeccio"], it: { type: "Sabbia chiara", access: "Facile", tips: "Ottima per famiglie, mare calmo con scirocco.", desc: "Spiaggia tranquilla vicina al porticciolo di San Nicola.", crowd: "Media", food: "Bar e ristoranti a due passi", seabed: "Basso e sabbioso", parking_info: "Misto: strisce blu estive sul lungomare e aree libere vicine alla stazione." }, en: { type: "Light sand", access: "Easy", tips: "Great for families, calm sea with South wind.", desc: "Quiet beach near the small port of San Nicola.", crowd: "Medium", food: "Bars and restaurants nearby", seabed: "Shallow and sandy", parking_info: "Mixed: summer paid blue zones on seafront & free spots near station." } },
  { id: "alcamo-marina", name: "Alcamo Marina", location: "Alcamo", prov: "TP", lat: 38.024, lng: 12.951, time: "15 min", dist: "15 km", kids: true, lidi: true, snorkel: false, park: true, parking_type: "free", wind_bad: ["Maestrale", "Tramontana", "Grecale"], wind_good: ["Scirocco", "Ostro", "Libeccio"], it: { type: "Sabbia dorata", access: "Molto Facile", tips: "Spiaggia immensa, ideale in alta stagione per trovare spazio.", desc: "Lunga distesa sabbiosa tra Balestrate e Castellammare.", crowd: "Alta, ma la spiaggia è vastissima", food: "Molti chioschi e pizzerie sul mare", seabed: "Basso, ideale per bambini", parking_info: "Gratuito lungo la SS113 e nelle vie parallele che portano al mare." }, en: { type: "Golden sand", access: "Very Easy", tips: "Huge beach, great in high season to find space.", desc: "Long sandy stretch between Balestrate and Castellammare.", crowd: "High, but the beach is huge", food: "Many kiosks and pizzerias on the sea", seabed: "Shallow, ideal for kids", parking_info: "Free along the SS113 coastal highway and side streets leading to the water." } },
  { id: "cala-petrolo", name: "Cala Petrolo", location: "Castellammare", prov: "TP", lat: 38.029, lng: 12.883, time: "30 min", dist: "28 km", kids: false, lidi: false, snorkel: true, park: false, parking_type: "paid", wind_bad: ["Grecale", "Tramontana"], wind_good: ["Scirocco", "Libeccio", "Ponente"], it: { type: "Ciottoli/Sabbia", access: "Scalinata", tips: "In pieno centro storico, parcheggio difficile.", desc: "Piccola caletta incastonata sotto il castello.", crowd: "Alta", food: "Tutto a disposizione in centro", seabed: "Misto ciottoli/sabbia, scende in fretta", parking_info: "A pagamento in Piazza Petrolo o nei parcheggi sotterranei del centro." }, en: { type: "Pebbles/Sand", access: "Stairs", tips: "Right in the historical center, difficult parking.", desc: "Small cove set just below the castle.", crowd: "High", food: "Everything available in the center", seabed: "Mixed pebbles/sand, drops quickly", parking_info: "Paid parking at Piazza Petrolo or underground garages nearby." } },
  { id: "mura-tramontana", name: "Mura di Tramontana", location: "Trapani", prov: "TP", lat: 38.016, lng: 12.509, time: "55 min", dist: "58 km", kids: true, lidi: false, snorkel: true, park: false, parking_type: "paid", wind_bad: ["Maestrale", "Tramontana", "Grecale"], wind_good: ["Scirocco", "Levante", "Ostro"], it: { type: "Sabbia fine", access: "Facile", tips: "Fai un bagno e poi goditi un aperitivo in centro storico.", desc: "Spiaggia magica sotto le antiche mura della città.", crowd: "Media", food: "Pieno centro storico di Trapani", seabed: "Basso e sabbioso", parking_info: "A pagamento (strisce blu lungo la via del porto o parcheggio Piazza Vittorio Emanuele)." }, en: { type: "Fine sand", access: "Easy", tips: "Swim then enjoy an aperitif in the old town.", desc: "Magical beach under the ancient city walls.", crowd: "Medium", food: "Right in Trapani's historical center", seabed: "Shallow and sandy", parking_info: "Paid blue lines along harbor road or Piazza Vittorio Emanuele lot." } },
  { id: "ciammarita", name: "Ciammarita", location: "Trappeto", prov: "PA", lat: 38.068, lng: 13.023, time: "5 min", dist: "2 km", kids: true, lidi: true, snorkel: false, park: true, parking_type: "free", wind_bad: ["Maestrale", "Tramontana", "Grecale"], wind_good: ["Scirocco", "Ostro", "Libeccio"], it: { type: "Sabbia dorata", access: "Facile", tips: "Parcheggio vicinissimo, la spiaggia di casa.", desc: "Spiaggia lunghissima e ventilata, a due passi dall'appartamento.", crowd: "Alta ad agosto", food: "Diversi lidi ristorante e bar", seabed: "Sabbioso, scende dolcemente", parking_info: "Gratuito su strada e nelle piazzuole dedicate a pochi metri dalla sabbia." }, en: { type: "Golden Sand", access: "Easy", tips: "Very close parking, the home beach.", desc: "Very long and breezy beach, steps from the apartment.", crowd: "High in August", food: "Several beach clubs and bars", seabed: "Sandy, slopes gently", parking_info: "Free roadside parking and dedicated turnouts just meters from the sand." } },
  { id: "balestrate", name: "Balestrate (Ovest)", location: "Balestrate", prov: "PA", lat: 38.051, lng: 12.985, time: "10 min", dist: "8 km", kids: true, lidi: true, snorkel: false, park: true, parking_type: "mixed", wind_bad: ["Maestrale", "Tramontana", "Grecale"], wind_good: ["Scirocco", "Ostro", "Libeccio"], it: { type: "Sabbia fine", access: "Facile", tips: "Pineta alle spalle per l'ombra.", desc: "Perfetta per lunghe passeggiate sul bagnasciuga.", crowd: "Alta in alta stagione", food: "Lidi attrezzati e chioschi", seabed: "Molto basso a riva", parking_info: "Misto: strisce blu in estate sul lungomare, aree gratuite vicino alla pineta." }, en: { type: "Fine Sand", access: "Easy", tips: "Pine forest behind for shade.", desc: "Perfect for long walks along the shore.", crowd: "High in peak season", food: "Equipped beach clubs and kiosks", seabed: "Very shallow near shore", parking_info: "Mixed: paid summer blue lines on promenade, free areas near pine forest." } },
  { id: "la-praiola", name: "La Praiola", location: "Terrasini", prov: "PA", lat: 38.155, lng: 13.08, time: "25 min", dist: "20 km", kids: false, lidi: false, snorkel: true, park: false, parking_type: "paid", wind_bad: ["Maestrale", "Tramontana", "Ponente"], wind_good: ["Scirocco", "Ostro", "Levante"], it: { type: "Sabbia scura/Scogli", access: "Scala", tips: "Vai al tramonto per i faraglioni.", desc: "Faraglioni e rocce rosse dal fascino selvaggio.", crowd: "Alta nei weekend", food: "Pieno centro di Terrasini", seabed: "Scende rapidamente", parking_info: "A pagamento (strisce blu in Piazza Duomo o nelle vie del centro di Terrasini)." }, en: { type: "Dark sand/Rocks", access: "Stairs", tips: "Go at sunset for the sea stacks.", desc: "Sea stacks and red rocks with wild charm.", crowd: "High on weekends", food: "Center of Terrasini", seabed: "Drops rapidly", parking_info: "Paid blue lines in Terrasini main square or surrounding downtown streets." } },
  { id: "magaggiari", name: "Magaggiari", location: "Cinisi", prov: "PA", lat: 38.163, lng: 13.097, time: "25 min", dist: "22 km", kids: true, lidi: true, snorkel: false, park: false, parking_type: "paid", wind_bad: ["Maestrale", "Tramontana", "Grecale"], wind_good: ["Scirocco", "Ostro", "Libeccio"], it: { type: "Sabbia", access: "Facile", tips: "Molto affollata nei weekend.", desc: "Sabbia bianca sotto la montagna.", crowd: "Altissima (Caos ad agosto)", food: "Ristoranti e cocktail bar sulla spiaggia", seabed: "Basso e sabbioso", parking_info: "Parcheggio comunale gestito a pagamento all'ingresso della spiaggia." }, en: { type: "Sand", access: "Easy", tips: "Very crowded on weekends.", desc: "White sand under the mountain.", crowd: "Very high (Chaos in August)", food: "Restaurants and cocktail bars on the beach", seabed: "Shallow and sandy", parking_info: "Municipal paid parking lot right at beach entrance." } },
  { id: "isola-femmine", name: "Isola delle Femmine", location: "Isola delle Femmine", prov: "PA", lat: 38.196, lng: 13.245, time: "35 min", dist: "35 km", kids: true, lidi: true, snorkel: false, park: true, parking_type: "paid", wind_bad: ["Tramontana", "Maestrale", "Grecale"], wind_good: ["Scirocco", "Ostro", "Libeccio"], it: { type: "Sabbia fine", access: "Facile", tips: "Tantissimi lidi attrezzati.", desc: "Lunga spiaggia con vista sull'isolotto.", crowd: "Altissima", food: "Piena di lidi, chioschi e pizzerie", seabed: "Molto basso", parking_info: "Strisce blu a pagamento su tutto il viale marittimo." }, en: { type: "Fine sand", access: "Easy", tips: "Many beach clubs available.", desc: "Long beach overlooking the islet.", crowd: "Very high", food: "Full of beach clubs, kiosks and pizzerias", seabed: "Very shallow", parking_info: "Paid blue lines along the entire coastal avenue." } },
  { id: "sferracavallo", name: "Sferracavallo", location: "Palermo", prov: "PA", lat: 38.199, lng: 13.275, time: "40 min", dist: "40 km", kids: false, lidi: false, snorkel: true, park: false, parking_type: "mixed", wind_bad: ["Tramontana", "Maestrale"], wind_good: ["Scirocco", "Levante", "Ostro"], it: { type: "Scogli/Rocce", access: "Media", tips: "Ottima per pesce fresco post-mare.", desc: "Acqua color smeraldo, fondali ricchi.", crowd: "Media", food: "Famosa per i ristoranti di pesce a prezzo fisso", seabed: "Roccioso, subito profondo", parking_info: "Misto: strisce blu nel borgo e piazzali liberi di interscambio verso Barcarello." }, en: { type: "Rocks", access: "Medium", tips: "Great for fresh seafood after.", desc: "Emerald water, rich seabed.", crowd: "Medium", food: "Famous for fixed-price fish restaurants", seabed: "Rocky, deep immediately", parking_info: "Mixed: paid blue lines in village center & free park-and-ride towards Barcarello." } },
  { id: "mondello", name: "Mondello", location: "Palermo", prov: "PA", lat: 38.204, lng: 13.325, time: "50 min", dist: "45 km", kids: true, lidi: true, snorkel: false, park: false, parking_type: "paid", wind_bad: ["Tramontana", "Grecale", "Levante"], wind_good: ["Scirocco", "Maestrale", "Ponente"], it: { type: "Sabbia caraibica", access: "Molto Facile", tips: "Bellissima con Maestrale.", desc: "La spiaggia VIP dei palermitani.", crowd: "Livelli critici nei fine settimana", food: "Street food, lidi storici, ristoranti di lusso", seabed: "Caraibico, bassissimo", parking_info: "A pagamento (strisce blu o parcheggi custoditi interni Viale Galatea)." }, en: { type: "Caribbean sand", access: "Very Easy", tips: "Beautiful with NW wind.", desc: "The VIP beach of Palermo.", crowd: "Critical levels on weekends", food: "Street food, historic clubs, luxury dining", seabed: "Caribbean, very shallow", parking_info: "Paid parking (blue lines or private guarded lots on Viale Galatea)." } },
  { id: "addaura", name: "Addaura", location: "Palermo", prov: "PA", lat: 38.188, lng: 13.348, time: "55 min", dist: "50 km", kids: false, lidi: true, snorkel: true, park: false, parking_type: "free", wind_bad: ["Grecale", "Levante", "Scirocco"], wind_good: ["Maestrale", "Ponente", "Libeccio"], it: { type: "Scogli", access: "Media", tips: "Lidi su palafitte molto chic.", desc: "Mare profondo alle pendici di Monte Pellegrino.", crowd: "Media (Alta in serale)", food: "Locali lounge e lidi su palafitte", seabed: "Scogli appuntiti, mare profondo", parking_info: "Gratuito lungo il Lungomare Cristoforo Colombo (spazi a pettine su strada)." }, en: { type: "Rocks", access: "Medium", tips: "Chic stilt-house beach clubs.", desc: "Deep sea under Mount Pellegrino.", crowd: "Medium (High in evening)", food: "Lounge bars and stilt beach clubs", seabed: "Sharp rocks, deep sea", parking_info: "Free parking along Lungomare Cristoforo Colombo street bays." } },
  { id: "torre-normanna", name: "Torre Normanna", location: "Altavilla Milicia", prov: "PA", lat: 38.046, lng: 13.553, time: "1h 10 min", dist: "85 km", kids: false, lidi: false, snorkel: true, park: true, parking_type: "free", wind_bad: ["Tramontana", "Maestrale"], wind_good: ["Scirocco", "Ostro"], it: { type: "Ciottoli", access: "Media", tips: "Acqua subito profonda.", desc: "Caletta sovrastata dall'antica torre.", crowd: "Tranquilla", food: "Resort/Hotel nelle vicinanze", seabed: "Ciottoli grandi, scende ripido", parking_info: "Gratuito lungo la bretella d'accesso vicina al residence/torre." }, en: { type: "Pebbles", access: "Medium", tips: "Water gets deep quickly.", desc: "Cove dominated by an ancient tower.", crowd: "Quiet", food: "Resort/Hotel nearby", seabed: "Large pebbles, drops steeply", parking_info: "Free parking along the access road near the tower/resort area." } },
  { id: "campofelice", name: "Campofelice di Roccella", location: "Campofelice", prov: "PA", lat: 37.994, lng: 13.882, time: "1h 20 min", dist: "105 km", kids: true, lidi: true, snorkel: false, park: true, parking_type: "free", wind_bad: ["Tramontana", "Grecale"], wind_good: ["Scirocco", "Ostro", "Libeccio"], it: { type: "Sabbia e Ciottoli", access: "Facile", tips: "Chilometri di spiaggia.", desc: "Ampia, adatta a chi non ama la folla.", crowd: "Media (ampi spazi)", food: "Villaggi turistici e qualche lido", seabed: "Misto, digradante", parking_info: "Gratuito e facilissimo su tutto il lungomare e negli spazi adiacenti al mare." }, en: { type: "Sand & Pebbles", access: "Easy", tips: "Kilometers of beach.", desc: "Wide, good for those avoiding crowds.", crowd: "Medium (wide spaces)", food: "Tourist villages and some clubs", seabed: "Mixed, sloping", parking_info: "Free and abundant parking all along the long coastal road." } },
  { id: "mazzaforno", name: "Mazzaforno", location: "Cefalù", prov: "PA", lat: 38.031, lng: 13.974, time: "1h 25 min", dist: "115 km", kids: true, lidi: true, snorkel: true, park: false, parking_type: "mixed", wind_bad: ["Maestrale", "Tramontana"], wind_good: ["Scirocco", "Ostro", "Libeccio"], it: { type: "Sabbia/Scogli", access: "Facile", tips: "Riparata dal vento di ponente.", desc: "Piccola baia molto suggestiva.", crowd: "Alta (spazio ristretto)", food: "Servizi di resort adiacenti", seabed: "Sabbia ai bordi, scogli al centro", parking_info: "Misto: pochi posti gratis su strada, parcheggi gestiti dai residence estivi." }, en: { type: "Sand/Rocks", access: "Easy", tips: "Sheltered from west wind.", desc: "Very suggestive small bay.", crowd: "High (limited space)", food: "Adjacent resort services", seabed: "Sand on edges, rocks in center", parking_info: "Mixed: limited free street parking or private resort parking areas." } },
  { id: "cefalu", name: "Cefalù Lungomare", location: "Cefalù", prov: "PA", lat: 38.035, lng: 14.015, time: "1h 30 min", dist: "120 km", kids: true, lidi: true, snorkel: false, park: false, parking_type: "paid", wind_bad: ["Maestrale", "Tramontana", "Grecale"], wind_good: ["Scirocco", "Ostro", "Libeccio"], it: { type: "Sabbia dorata", access: "Facile", tips: "Parcheggia fuori centro.", desc: "Vista mozzafiato sulla cattedrale.", crowd: "Altissima, affollata", food: "Tutto: bar, ristoranti, gelaterie", seabed: "Sabbioso, scende gradualmente", parking_info: "A pagamento su tutto il lungomare (strisce blu o parcheggi custoditi)." }, en: { type: "Golden sand", access: "Easy", tips: "Park outside center.", desc: "Stunning view of the cathedral.", crowd: "Very high, crowded", food: "Everything: bars, restaurants, gelato", seabed: "Sandy, drops gradually", parking_info: "Paid along entire promenade (blue lines or daily private lots)." } },
  { id: "torre-conca", name: "Torre Conca", location: "Pollina", prov: "PA", lat: 38.026, lng: 14.153, time: "1h 45 min", dist: "135 km", kids: false, lidi: true, snorkel: true, park: true, parking_type: "paid", wind_bad: ["Tramontana", "Grecale"], wind_good: ["Scirocco", "Ostro", "Libeccio"], it: { type: "Ghiaia/Sabbia scura", access: "Facile", tips: "Una delle più belle della costa est.", desc: "Mare cristallino al confine con Messina.", crowd: "Alta", food: "Chioschi e servizi in loco", seabed: "Scende quasi subito", parking_info: "Parcheggio gestito a pagamento a monte della caletta." }, en: { type: "Gravel/Dark sand", access: "Easy", tips: "One of the best on the east coast.", desc: "Crystal water on the Messina border.", crowd: "High", food: "Kiosks and services on site", seabed: "Drops almost immediately", parking_info: "Guarded paid parking lot above the cove." } },
  { id: "la-playa", name: "La Playa", location: "Castellammare", prov: "TP", lat: 38.027, lng: 12.905, time: "25 min", dist: "25 km", kids: true, lidi: true, snorkel: false, park: true, parking_type: "paid", wind_bad: ["Maestrale", "Tramontana", "Grecale"], wind_good: ["Scirocco", "Ostro", "Libeccio"], it: { type: "Sabbia dorata", access: "Molto Facile", tips: "Lidi immensi e fondale basso.", desc: "La spiaggia più grande del golfo.", crowd: "Altissima ad agosto", food: "Lidi completi, ristoranti, pizzerie", seabed: "Basso e sicuro per i bimbi", parking_info: "Strisce blu su tutto il lungomare e ampi parcheggi privati di fronte ai lidi." }, en: { type: "Golden sand", access: "Very Easy", tips: "Huge beach clubs, shallow water.", desc: "The largest beach in the gulf.", crowd: "Very high in August", food: "Full beach clubs, restaurants", seabed: "Shallow and safe for kids", parking_info: "Paid blue lines on promenade and private beach lots." } },
  { id: "guidaloca", name: "Guidaloca", location: "Scopello", prov: "TP", lat: 38.058, lng: 12.836, time: "40 min", dist: "32 km", kids: true, lidi: true, snorkel: true, park: true, parking_type: "paid", wind_bad: ["Scirocco", "Levante", "Ostro"], wind_good: ["Tramontana", "Maestrale", "Ponente"], it: { type: "Ciottoli lisci", access: "Facile", tips: "Baia molto riparata.", desc: "Acqua trasparente e lidi attrezzati.", crowd: "Molto Alta", food: "Diversi bar e servizi di noleggio lettini", seabed: "Ciottoli, digradante", parking_info: "Grandi parcheggi custoditi a pagamento adiacenti alla spiaggia." }, en: { type: "Smooth pebbles", access: "Easy", tips: "Very sheltered bay.", desc: "Clear water and beach clubs.", crowd: "Very High", food: "Several bars and sunbed rentals", seabed: "Pebbles, sloping", parking_info: "Large guarded paid parking lots right next to the beach." } },
  { id: "zingaro", name: "Riserva dello Zingaro", location: "Scopello", prov: "TP", lat: 38.093, lng: 12.801, time: "45 min", dist: "35 km", kids: false, lidi: false, snorkel: true, park: true, parking_type: "paid", wind_bad: ["Scirocco", "Levante", "Grecale"], wind_good: ["Maestrale", "Ponente", "Libeccio"], it: { type: "Ciottoli", access: "Trekking", tips: "Acqua e scarpe chiuse. Ingresso a pagamento.", desc: "Calette incontaminate nella riserva naturale.", crowd: "Media/Alta (Ingressi a numero chiuso)", food: "Niente servizi. Portare pranzo al sacco e molta acqua", seabed: "Roccioso e profondo", parking_info: "Parcheggio ufficiale a pagamento all'ingresso Nord e Sud della riserva." }, en: { type: "Pebbles", access: "Trekking", tips: "Bring water & sneakers. Ticket needed.", desc: "Pristine nature reserve coves.", crowd: "Medium/High (Limited entries)", food: "No services. Bring packed lunch and lots of water", seabed: "Rocky and deep", parking_info: "Official paid parking lot at North and South entrances." } },
  { id: "san-vito-lo-capo", name: "San Vito Lo Capo", location: "San Vito Lo Capo", prov: "TP", lat: 38.175, lng: 12.733, time: "1h", dist: "55 km", kids: true, lidi: true, snorkel: false, park: false, parking_type: "paid", wind_bad: ["Tramontana", "Grecale"], wind_good: ["Scirocco", "Ostro", "Libeccio"], it: { type: "Sabbia bianca", access: "Facile", tips: "Affollata, vai presto.", desc: "Il Monte Monaco protegge dai venti la spiaggia caraibica.", crowd: "Caotica a luglio e agosto", food: "L'intero paese alle spalle della spiaggia", seabed: "Bianchissimo e bassissimo", parking_info: "A pagamento (strisce blu in paese e grandi parcheggi scambiatori)." }, en: { type: "White sand", access: "Easy", tips: "Crowded, go early.", desc: "Monte Monaco protects the Caribbean-like beach from winds.", crowd: "Chaotic in July and August", food: "The whole town right behind the beach", seabed: "Very white and very shallow", parking_info: "Paid parking (town blue lines and large park-and-ride lots)." } },
  { id: "santa-margherita", name: "Baia Santa Margherita", location: "Macari", prov: "TP", lat: 38.125, lng: 12.729, time: "55 min", dist: "52 km", kids: true, lidi: true, snorkel: true, park: true, parking_type: "free", wind_bad: ["Maestrale", "Ponente", "Libeccio"], wind_good: ["Scirocco", "Levante", "Grecale"], it: { type: "Sabbia/Scogli", access: "Trenino gratis", tips: "Tramonti pazzeschi.", desc: "La vera alternativa a San Vito, più tranquilla.", crowd: "Media", food: "Un chioschetto bar per bibite e gelati", seabed: "Misto sabbia/rocce, subito profondo ai lati", parking_info: "Gratuito e grandissimo all'ingresso della baia + Trenino navetta gratuito fino alle calette!" }, en: { type: "Sand/Rocks", access: "Free shuttle", tips: "Crazy sunsets.", desc: "The real, quieter alternative to San Vito.", crowd: "Medium", food: "A small kiosk for drinks and ice cream", seabed: "Mixed sand/rocks, deep quickly on sides", parking_info: "Free huge main parking lot + Free shuttle train running to all the small coves!" } },
  { id: "cornino", name: "Baia di Cornino", location: "Custonaci", prov: "TP", lat: 38.097, lng: 12.658, time: "50 min", dist: "45 km", kids: false, lidi: true, snorkel: true, park: true, parking_type: "paid", wind_bad: ["Maestrale", "Ponente", "Libeccio"], wind_good: ["Scirocco", "Levante", "Grecale"], it: { type: "Sabbia e Scogli", access: "Facile", tips: "Sotto il Monte Cofano.", desc: "Spettacolare al tramonto sotto il promontorio.", crowd: "Media", food: "Diversi chioschi/ristorantini sul mare", seabed: "Digradante", parking_info: "Strisce blu a pagamento lungo tutto il porticciolo e sotto la riserva." }, en: { type: "Sand & Rocks", access: "Easy", tips: "Under Mount Cofano.", desc: "Spectacular at sunset under the headland.", crowd: "Medium", food: "Several kiosks/restaurants by the sea", seabed: "Sloping", parking_info: "Paid blue lines along the small harbor and below the nature reserve." } },
  { id: "pizzolungo", name: "Pizzolungo", location: "Erice", prov: "TP", lat: 38.041, lng: 12.559, time: "55 min", dist: "60 km", kids: false, lidi: false, snorkel: true, park: true, parking_type: "free", wind_bad: ["Maestrale", "Ponente", "Tramontana"], wind_good: ["Scirocco", "Levante", "Ostro"], it: { type: "Scogliera", access: "Media", tips: "Usa le scarpette da scoglio.", desc: "Mare profondo perfetto per lo snorkeling.", crowd: "Bassa/Tranquilla", food: "Pochi servizi sulla costa, organizzarsi", seabed: "Scogli appuntiti, profondo", parking_info: "Gratuito e facile lungo gli spiazzi della strada statale costiera." }, en: { type: "Cliffs", access: "Medium", tips: "Use water shoes.", desc: "Deep sea perfect for snorkeling.", crowd: "Low/Quiet", food: "Few services on the coast, prepare ahead", seabed: "Sharp rocks, deep", parking_info: "Free and easy parking in turnouts along the coastal road." } },
  { id: "san-giuliano", name: "San Giuliano", location: "Trapani", prov: "TP", lat: 38.031, lng: 12.529, time: "50 min", dist: "55 km", kids: true, lidi: true, snorkel: false, park: true, parking_type: "paid", wind_bad: ["Maestrale", "Ponente", "Libeccio"], wind_good: ["Scirocco", "Levante", "Grecale"], it: { type: "Sabbia", access: "Facile", tips: "Acqua calda e cristallina.", desc: "La spiaggia principale di Trapani.", crowd: "Alta", food: "Lidi storici e chioschi abbondanti", seabed: "Sabbioso, digradante", parking_info: "Strisce blu estive lungo l'intero lungomare Dante Alighieri." }, en: { type: "Sand", access: "Easy", tips: "Warm and crystal water.", desc: "The main beach of Trapani.", crowd: "High", food: "Historic beach clubs and abundant kiosks", seabed: "Sandy, sloping", parking_info: "Summer paid blue lines along the Dante Alighieri seafront." } },
  { id: "lido-signorino", name: "Lido Signorino", location: "Marsala", prov: "TP", lat: 37.742, lng: 12.458, time: "1h 10 min", dist: "85 km", kids: true, lidi: true, snorkel: false, park: true, parking_type: "free", wind_bad: ["Libeccio", "Ponente", "Scirocco"], wind_good: ["Tramontana", "Grecale", "Levante"], it: { type: "Sabbia fine", access: "Facile", tips: "Ideale per i bambini.", desc: "Acqua molto bassa e calda.", crowd: "Alta, molto amata dai locali", food: "Numerosi lidi attrezzati con ristorazione", seabed: "Sabbioso, eccezionalmente basso", parking_info: "Gratuito lungo le strade d'accesso ai lidi o negli spiazzi sterrati vicini." }, en: { type: "Fine sand", access: "Easy", tips: "Ideal for kids.", desc: "Very shallow and warm water.", crowd: "High, loved by locals", food: "Numerous equipped clubs with food", seabed: "Sandy, exceptionally shallow", parking_info: "Free street parking along beach access roads and nearby dirt lots." } },
  { id: "tonnarella", name: "Tonnarella", location: "Mazara del Vallo", prov: "TP", lat: 37.643, lng: 12.564, time: "1h 10 min", dist: "75 km", kids: true, lidi: true, snorkel: false, park: true, parking_type: "free", wind_bad: ["Scirocco", "Ostro", "Libeccio"], wind_good: ["Tramontana", "Maestrale", "Grecale"], it: { type: "Sabbia bianca", access: "Molto Facile", tips: "Piatta con vento da Nord.", desc: "Mare basso e caldo, adatta alle famiglie.", crowd: "Alta", food: "Piena di lidi con animazione e ristoranti", seabed: "Sabbioso e poco profondo", parking_info: "Gratuito su tutta la via Hopps e nel lungomare della Tonnarella." }, en: { type: "White sand", access: "Very Easy", tips: "Flat with North wind.", desc: "Shallow and warm sea, family friendly.", crowd: "High", food: "Full of clubs with animation and food", seabed: "Sandy and shallow", parking_info: "Free parking along the main beach avenue and surrounding streets." } },
  { id: "tre-fontane", name: "Tre Fontane", location: "Campobello", prov: "TP", lat: 37.571, lng: 12.723, time: "1h 15 min", dist: "80 km", kids: true, lidi: true, snorkel: false, park: true, parking_type: "free", wind_bad: ["Scirocco", "Ostro", "Libeccio"], wind_good: ["Tramontana", "Maestrale", "Grecale"], it: { type: "Sabbia dorata", access: "Molto Facile", tips: "Spazi immensi.", desc: "Acqua bassissima per centinaia di metri.", crowd: "Media (Spazi grandissimi)", food: "Gelaterie e pizzerie nella piazza adiacente", seabed: "Bassissimo per centinaia di metri", parking_info: "Gratuito nelle vie a scacchiera del villaggio vicinissime al mare." }, en: { type: "Golden sand", access: "Very Easy", tips: "Huge open spaces.", desc: "Very shallow water for hundreds of meters.", crowd: "Medium (Very large spaces)", food: "Ice cream shops and pizzerias in adjacent square", seabed: "Very shallow for hundreds of meters", parking_info: "Free street parking in the village grid right by the sand." } },
  { id: "marinella-selinunte", name: "Marinella di Selinunte", location: "Castelvetrano", prov: "TP", lat: 37.581, lng: 12.835, time: "1h 10 min", dist: "75 km", kids: true, lidi: true, snorkel: false, park: true, parking_type: "paid", wind_bad: ["Scirocco", "Ostro", "Libeccio"], wind_good: ["Tramontana", "Maestrale", "Grecale"], it: { type: "Sabbia e argilla", access: "Facile", tips: "Vista sui templi greci.", desc: "Spiaggia incantevole sotto la riserva archeologica.", crowd: "Alta in zona centro", food: "Ristorantini di pesce sul molo", seabed: "Sabbioso, digradante", parking_info: "Strisce blu a pagamento vicino al porticciolo e all'ingresso del Parco Archeologico." }, en: { type: "Sand and clay", access: "Easy", tips: "View of the Greek temples.", desc: "Enchanting beach under the archaeological reserve.", crowd: "High in center area", food: "Small fish restaurants on the pier", seabed: "Sandy, sloping", parking_info: "Paid blue lines near small harbor and Archaeological Park entrance." } },
  { id: "cala-rossa-favignana", name: "Cala Rossa (Favignana)", location: "Favignana", prov: "TP", lat: 37.922, lng: 12.355, time: "1h 45 min", dist: "Aliscafo da Trapani", kids: false, lidi: false, snorkel: true, park: false, parking_type: "free", wind_bad: ["Grecale", "Levante", "Tramontana"], wind_good: ["Scirocco", "Libeccio", "Ponente", "Ostro"], it: { type: "Scogli/Rocce", access: "Media", tips: "Aliscafo da Trapani + Bici/Scooter. Scarpette consigliate.", desc: "La più famosa dell'isola. Mare azzurro e cave di tufo.", crowd: "Altissima (Andare presto!)", food: "Barche che vendono granite/pane cunzato", seabed: "Acqua subito profonda e rocciosa", parking_info: "Gratuito per bici e scooter alla fine della strada sterrata (Isola in ZTL per auto non residenti)." }, en: { type: "Rocks", access: "Medium", tips: "Hydrofoil from Trapani + Bike/Scooter. Water shoes needed.", desc: "The most famous. Blue sea and tuff quarries.", crowd: "Very High (Go early!)", food: "Boats selling local snacks/drinks", seabed: "Deep and rocky immediately", parking_info: "Free parking for bikes and scooters at end of dirt road (Car ZTL active on island)." } },
  { id: "cala-azzurra", name: "Cala Azzurra", location: "Favignana", prov: "TP", lat: 37.905, lng: 12.345, time: "1h 45 min", dist: "Aliscafo da Trapani", kids: true, lidi: false, snorkel: true, park: false, parking_type: "free", wind_bad: ["Scirocco", "Levante", "Ostro"], wind_good: ["Tramontana", "Maestrale", "Ponente"], it: { type: "Sabbia bianca", access: "Facile", tips: "Serve aliscafo/traghetto da Trapani.", desc: "Acqua trasparente e sabbia bianca come ai Caraibi.", crowd: "Altissima, spazi limitati", food: "Chioschetto estivo", seabed: "Sabbioso e molto basso", parking_info: "Gratuito per bici/scooter nello spiazzo dedicato sopra la caletta." }, en: { type: "White sand", access: "Easy", tips: "Requires hydrofoil/ferry from Trapani.", desc: "Transparent water and white sand like the Caribbean.", crowd: "Very high, limited space", food: "Summer kiosk", seabed: "Sandy and very shallow", parking_info: "Free bike/scooter parking area right above the cove." } },
  { id: "lido-burrone", name: "Lido Burrone", location: "Favignana", prov: "TP", lat: 37.914, lng: 12.332, time: "1h 45 min", dist: "Aliscafo da Trapani", kids: true, lidi: true, snorkel: false, park: false, parking_type: "free", wind_bad: ["Scirocco", "Ostro", "Libeccio"], wind_good: ["Tramontana", "Maestrale", "Grecale"], it: { type: "Sabbia fine", access: "Facile", tips: "Unica vera spiaggia attrezzata grande dell'isola.", desc: "Comoda per famiglie, acqua bassissima.", crowd: "Alta", food: "Lido ristorante completo", seabed: "Sabbioso e sicuro", parking_info: "Gratuito per bici/scooter + Capolinea bus navetta pubblico dall'imbarcadero." }, en: { type: "Fine sand", access: "Easy", tips: "The only large equipped beach on the island.", desc: "Comfortable for families, very shallow water.", crowd: "High", food: "Full beach club and restaurant", seabed: "Sandy and safe", parking_info: "Free bike/scooter parking + Public bus stop directly connected to ferry port." } },
  { id: "bue-marino", name: "Bue Marino", location: "Favignana", prov: "TP", lat: 37.918, lng: 12.361, time: "1h 45 min", dist: "Aliscafo da Trapani", kids: false, lidi: false, snorkel: true, park: false, parking_type: "free", wind_bad: ["Levante", "Scirocco", "Grecale"], wind_good: ["Ponente", "Maestrale", "Libeccio", "Tramontana"], it: { type: "Scogliera/Tufo", access: "Media", tips: "Ideale per i tuffi e lo snorkeling avanzato.", desc: "Fondale profondo tra suggestive cave di tufo sul mare.", crowd: "Media", food: "Spesso food truck nel piazzale", seabed: "Profondissimo per immersioni", parking_info: "Gratuito per bici e scooter nello spiazzo panoramico sopra le cave." }, en: { type: "Cliffs/Tuff", access: "Medium", tips: "Ideal for diving and advanced snorkeling.", desc: "Deep seabed among suggestive tuff quarries by the sea.", crowd: "Medium", food: "Often a food truck in the parking area", seabed: "Very deep for diving", parking_info: "Free bike and scooter turnout above the quarries." } },
  { id: "cala-rotonda", name: "Cala Rotonda", location: "Favignana", prov: "TP", lat: 37.917, lng: 12.298, time: "1h 45 min", dist: "Aliscafo da Trapani", kids: false, lidi: false, snorkel: true, park: false, parking_type: "free", wind_bad: ["Ponente", "Maestrale", "Libeccio"], wind_good: ["Scirocco", "Levante", "Grecale", "Tramontana"], it: { type: "Ciottoli", access: "Media", tips: "Riparata quando l'isola è battuta da altri venti.", desc: "Porticciolo naturale con l'Arco di Ulisse in pietra.", crowd: "Media/Bassa", food: "Nessun servizio", seabed: "Ciottoli e massi subacquei", parking_info: "Gratuito per bici e scooter nello sterrato a ridosso dell'insenatura." }, en: { type: "Pebbles", access: "Medium", tips: "Sheltered when the island is hit by other winds.", desc: "Natural small port with the stone Arch of Ulysses.", crowd: "Medium/Low", food: "No services", seabed: "Pebbles and underwater boulders", parking_info: "Free dirt area for bikes and scooters right behind the inlet." } },
];

// Nome del vento italiano dai gradi bussola (0=N).
const WIND_NAMES = ["Tramontana", "Grecale", "Levante", "Scirocco", "Ostro", "Libeccio", "Ponente", "Maestrale"];
const WIND_LABELS = ["Tramontana (N)", "Grecale (NE)", "Levante (E)", "Scirocco (SE)", "Ostro (S)", "Libeccio (SW)", "Ponente (W)", "Maestrale (NW)"];

export function windFromDegrees(deg: number): { name: string; label: string } {
  const i = Math.round((deg % 360) / 45) % 8;
  return { name: WIND_NAMES[i], label: WIND_LABELS[i] };
}

export type BeachStatus = "recommended" | "avoid" | "neutral";
export function analyzeBeach(beach: Beach, windName: string): BeachStatus {
  if (beach.wind_bad.includes(windName)) return "avoid";
  if (beach.wind_good.includes(windName)) return "recommended";
  return "neutral";
}
