export type Dish = {
  id: string;
  category: string;
  name: string;
  region: string;
  description: string;
  ingredients: string[];
  funFact: string;
  icon: string;
};

export const culinaryData: Dish[] = [
  { id: "arancina", category: "Palermo", name: "Arancina (al burro o alla carne)", region: "Palermo", description: 'A Palermo è rigorosamente femmina! La versione "al burro" con besciamella e prosciutto o quella classica alla carne con ragù e piselli, racchiuse in una croccante panatura dorata.', ingredients: ["Riso Carnaroli", "Zafferano", "Besciamella o Ragù", "Piselli o Prosciutto", "Pangrattato"], funFact: 'Il 13 dicembre (Santa Lucia) a Palermo si consumano milioni di arancine, celebrando il "no" a pane e pasta.', icon: "🍘" },
  { id: "pane-ca-meusa", category: "Palermo", name: "Pane ca Meusa", region: "Palermo", description: "Il panino definitivo di Palermo: una morbida pagnotta con sesamo (vastedda) farcita con milza e polmone di vitello bolliti e poi soffritti nello strutto.", ingredients: ["Pagnotta con sesamo", "Milza e polmone di vitello", "Strutto", "Limone o Caciocavallo"], funFact: 'Si ordina "Schietto" (con limone) o "Maritato" (con caciocavallo e ricotta grattugiati).', icon: "🍔" },
  { id: "panelle", category: "Palermo", name: "Panelle", region: "Palermo", description: "Sottili e croccanti frittelle fatte con farina di ceci, acqua, sale e prezzemolo, servite calde dentro un panino morbido con sesamo (mafalda).", ingredients: ["Farina di ceci", "Acqua", "Prezzemolo", "Sale e Pepe", "Panino con sesamo"], funFact: "Spesso si gustano insieme alle crocchè di patate (cazzilli) nello stesso panino con una spruzzata di limone.", icon: "🥪" },
  { id: "crocche", category: "Palermo", name: "Crocchè (Cazzilli)", region: "Palermo", description: "Deliziose crocchette di patate aromatizzate con foglioline di menta fresca, modellate a mano e fritte fino a doratura.", ingredients: ["Patate", "Menta fresca", "Uovo", "Pangrattato", "Olio per friggere"], funFact: 'A Palermo sono popolarmente chiamate "cazzilli" per via della loro forma allungata tipica.', icon: "🥔" },
  { id: "stigghiola", category: "Palermo", name: "Stigghiola", region: "Palermo", description: "Budella di vitello o agnello accuratamente lavate, insaporite con cipollotto e prezzemolo, infilzate in spiedini e arrostite sulla brace viva.", ingredients: ["Budella di vitello o agnello", "Cipollotto fresco", "Prezzemolo", "Sale", "Limone"], funFact: 'Le postazioni degli "stigghiulari" riempiono le strade di Palermo con un inconfondibile e profumato fumo bianco.', icon: "🍢" },
  { id: "frittola", category: "Palermo", name: "Frittola", region: "Palermo", description: "Un antico cibo di strada preparato con i pezzetti di carne di vitello residui della macellazione, bolliti, aromatizzati con strutto, pepe, alloro e limone.", ingredients: ["Resti di vitello bolliti", "Strutto", "Alloro", "Pepe nero", "Succo di limone"], funFact: 'Il "frittularu" trasporta la frittola calda in una caratteristica cesta di vimini coperta da una tela bianca (panaru).', icon: "🍖" },
  { id: "sfincione-palermitano", category: "Palermo", name: "Sfincione palermitano", region: "Palermo", description: "Il re dello street food: una sofficissima focaccia alta e spugnosa, condita con salsa ricca di cipolle, sarde salate, caciocavallo e mollica tostata.", ingredients: ["Farina e lievito", "Cipolle bianche", "Sarde", "Salsa di pomodoro", "Caciocavallo", "Pangrattato"], funFact: "Il venditore ambulante lo pubblicizzava un tempo con una famosa abbanniata a squarciagola.", icon: "🍕" },
  { id: "pasta-sarde", category: "Palermo", name: "Pasta con le sarde", region: "Palermo", description: "Il capolavoro arabo-normanno che unisce il pesce azzurro ai profumi della montagna con finocchietto selvatico, pinoli, uvetta e zafferano.", ingredients: ["Bucatini", "Sarde fresche", "Finocchietto selvatico", "Pinoli e Uvetta", "Zafferano", "Muddica tostata"], funFact: 'La mollica tostata sopra (muddica atturrata) viene storicamente definita "il formaggio dei poveri".', icon: "🍝" },
  { id: "anelletti-forno", category: "Palermo", name: "Anelletti al forno", region: "Palermo", description: "Il timballo della domenica. Pasta a forma di anello immersa in un ragù denso di carne e piselli, arricchita con caciocavallo e cotta al forno.", ingredients: ["Pasta Anelletti", "Ragù di carne", "Piselli", "Caciocavallo", "Pangrattato"], funFact: "È il piatto immancabile per le gite fuori porta o le giornate al mare dei palermitani.", icon: "🥘" },
  { id: "sarde-beccafico", category: "Palermo", name: "Sarde a beccafico", region: "Palermo", description: "Involtini di sarde fresche farciti con un ripieno dolce-salato di pangrattato, uvetta, pinoli e scorza d'agrumi, cotti al forno con foglie d'alloro.", ingredients: ["Sarde diliscate", "Pangrattato", "Uvetta e Pinoli", "Succo d'arancia", "Alloro"], funFact: 'Nacque come imitazione popolare dei pregiati uccelletti "beccafico" che i nobili cacciavano nei boschi.', icon: "🐟" },
  { id: "involtini-palermitana", category: "Palermo", name: "Involtini alla palermitana", region: "Palermo", description: "Fettine sottili di vitello ripiene di caciocavallo, uva passa, pinoli e mollica, impanate e infilzate negli spiedini alternate con cipolla e alloro.", ingredients: ["Fettine di vitello", "Pangrattato", "Caciocavallo", "Uva passa e Pinoli", "Alloro e Cipolla"], funFact: "Il segreto della cottura perfetta è farli arrostire lentamente sulla brace o sulla piastra rovente.", icon: "🍢" },
  { id: "cassata", category: "Palermo", name: "Cassata siciliana", region: "Palermo", description: "Trionfo barocco della pasticceria: pan di spagna inzuppato di liquore, crema di ricotta di pecora zuccherata, pasta reale verde e ricca frutta candita.", ingredients: ["Ricotta di pecora", "Pan di Spagna", "Pasta reale (Marzapane)", "Frutta candita", "Glassa di zucchero"], funFact: 'Il nome deriva dall\'arabo "qas\'at" (bacinella), contenitore originario usato per mescolare la ricotta.', icon: "🎂" },
  { id: "frutta-martorana", category: "Palermo", name: "Frutta Martorana", region: "Palermo", description: "Meravigliosi dolcetti di pasta di mandorle modellati e dipinti a mano per imitare in modo perfetto frutta, agrumi e ortaggi.", ingredients: ["Farina di mandorle", "Zucchero a velo", "Acqua", "Coloranti alimentari naturali"], funFact: "Inventata dalle monache del convento della Martorana per abbellire gli alberi spogli in autunno.", icon: "🍋" },
  { id: "sfincia-san-giuseppe", category: "Palermo", name: "Sfincia di San Giuseppe", region: "Palermo", description: "Soffice e porosa frittella tradizionale, ricoperta da una generosa crema di ricotta di pecora, granella di pistacchio e canditi.", ingredients: ["Pasta choux fritta", "Crema di ricotta", "Granella di pistacchio", "Ciliegie candite", "Scorze d'arancia"], funFact: "Celebra tradizionalmente la festa del papà e di San Giuseppe il 19 marzo.", icon: "🥯" },
  { id: "gelo-mellone", category: "Palermo", name: "Gelo di Mellone", region: "Palermo", description: "Fresco e profumato budino estivo preparato con succo puro di anguria (mellone), amido, cannella, gocce di cioccolato e petali di gelsomino.", ingredients: ["Succo di anguria", "Amido di frumento", "Zucchero", "Gocce di cioccolato", "Gelsomino"], funFact: "Le gocce di cioccolato inserite nel budino simulano perfettamente i semi neri dell'anguria.", icon: "🍉" },
  { id: "iris", category: "Palermo", name: "Iris (fritta o al forno)", region: "Palermo", description: "Morbida pasta brioche tonda, farcita con crema dolce di ricotta e cioccolato, passata nella pastella e fritta (o cotta al forno).", ingredients: ["Impasto brioche", "Crema di ricotta zuccherata", "Cioccolato fondente", "Pastella"], funFact: 'Nata a Palermo nel 1901 in occasione della prima rappresentazione dell\'opera "Iris" di Pietro Mascagni.', icon: "🍩" },
  { id: "ravazzata", category: "Palermo", name: "Ravazzata", region: "Palermo", description: "Un pezzo di rosticceria classica palermitana: pasta brioche dolce al forno ripiena di saporito ragù di carne e piselli.", ingredients: ["Pasta brioche", "Ragù di carne", "Piselli", "Uovo per dorare"], funFact: "Spesso gustata caldissima la mattina per colazione o come spuntino pomeridiano nei bar.", icon: "🥐" },
  { id: "rollo", category: "Palermo", name: "Rollò", region: "Palermo", description: "Un wurstel intero avvolto in soffice pasta brioche dolce, spennellato con uovo e ricoperto di semi di sesamo prima della cottura.", ingredients: ["Pasta brioche", "Wurstel di qualità", "Semi di sesamo", "Uovo"], funFact: "È uno dei pezzi di rosticceria preferiti dai bambini durante le feste di compleanno.", icon: "🌭" },
  { id: "calzone", category: "Palermo", name: "Calzone", region: "Palermo", description: "Rustico di pasta brioche ripieno di prosciutto cotto e mozzarella filante, disponibile nella versione fritta (dorata e croccante) o al forno.", ingredients: ["Pasta brioche", "Prosciutto cotto", "Mozzarella o Provola", "Uovo (per la versione al forno)"], funFact: "Nella versione fritta assume una forma a mezzaluna chiusa con i rebbi della forchetta.", icon: "🥟" },
  { id: "babbaluci", category: "Palermo", name: "Babbaluci", region: "Palermo", description: "Lumachine di terra cucinate con un ricco soffritto di aglio, olio extravergine d'oliva, prezzemolo fresco e sfumate con vino bianco.", ingredients: ["Lumachine di terra", "Aglio", "Olio d'oliva", "Prezzemolo", "Vino bianco"], funFact: "Sono il piatto immancabile e folkloristico delle serate estive e del Festino di Santa Rosalia.", icon: "🐌" },
  { id: "quarume", category: "Palermo", name: "Quarume (Caldume)", region: "Palermo", description: "Storico e robusto brodo caldo preparato con le interiora di vitello (centopelli, ziniere, saccoccia), cotte a lungo con verdure e aromi.", ingredients: ["Interiora di vitello", "Cipolla", "Carote", "Sedano", "Prezzemolo e Peperoncino"], funFact: 'Venduto storicamente nei mercati dai "quarumari", è considerato un vero comfort food invernale.', icon: "🍲" },
  { id: "caponata-palermitana", category: "Palermo", name: "Caponata Palermitana", region: "Palermo", description: "Il celebre antipasto agrodolce a base di melanzane fritte, sedano, cipolla, capperi e olive verdi, legato da una salsa agrodolce di pomodoro e aceto.", ingredients: ["Melanzane", "Sedano", "Cipolle", "Capperi e Olive verdi", "Aceto e Zucchero", "Pomodoro"], funFact: 'La leggenda vuole che il nome derivi dalle "cauponae", le antiche taverne romane.', icon: "🍆" },
  { id: "brociolone", category: "Palermo", name: "Brociolone (Falsomagro)", region: "Palermo", description: "Un grande rotolo di carne bovina ripieno di uova sode, caciocavallo, mortadella o salame e pangrattato, brasato lentamente nel sugo.", ingredients: ["Fettina grande di manzo", "Uova sode", "Mortadella", "Caciocavallo", "Sugo di pomodoro"], funFact: 'Il nome ironico "falsomagro" deriva dal fatto che all\'apparenza sembra magro ma nasconde un ripieno ricchissimo.', icon: "🥩" },
  { id: "muffuletta", category: "Palermo", name: "Muffuletta", region: "Palermo", description: "Morbida pagnotta tonda aromatizzata con semi di finocchietto selvatico, tradizionalmente gustata il giorno di San Martino.", ingredients: ["Farina e Lievito", "Semi di finocchietto", "Olio d'oliva", "Acciughe e Caciocavallo"], funFact: "Si mangia calda condita con olio, sale, pepe, acciughe e caciocavallo, oppure con ricotta fresca.", icon: "🥖" },
  { id: "purpu-vugghiutu", category: "Palermo", name: "Purpu vugghiutu", region: "Palermo", description: "Polpo fresco bollito alla perfezione nei chioschi delle borgate marinare (Mondello e Sferracavallo) e servito a pezzi con limone.", ingredients: ["Polpo fresco", "Sale", "Limone fresco", "Prezzemolo"], funFact: 'Nei banconi dei mercati storici si grida ancora: "Bevi che è brodo di polpo!"', icon: "🐙" },
  { id: "spaghetti-ricci", category: "Palermo", name: "Spaghetti ai ricci di mare", region: "Palermo", description: "Un primo piatto marino di lusso assoluto, condito a crudo con i preziosi coralli dei ricci di mare raccolti lungo le coste rocciose.", ingredients: ["Spaghetti", "Polpa di ricci di mare", "Aglio", "Olio extravergine", "Prezzemolo"], funFact: "Il sugo non va mai cotto: il calore della pasta appena scolata basta a esaltare la dolcezza iodata dei ricci.", icon: "🍝" },
  { id: "sfincione-bagherese", category: "Bagheria", name: "Sfincione bagherese", region: "Bagheria (PA)", description: "La variante bianca e raffinata dello sfincione. Niente pomodoro: l'impasto accoglie tuma fresca, ricotta, cipolla stufata, acciughe e mollica tostata.", ingredients: ["Pasta da focaccia", "Tuma fresca", "Ricotta", "Cipolla appassita", "Acciughe", "Mollica"], funFact: "Era il piatto principe delle feste patronali e natalizie nelle famiglie di Bagheria.", icon: "🥖" },
  { id: "cannolo-piana", category: "Piana degli Albanesi", name: "Cannolo di Piana", region: "Piana degli Albanesi (PA)", description: "Famoso in tutta la Sicilia per le dimensioni generose e la croccantezza ineguagliabile della cialda fritta, ripiena di vellutata ricotta di pecora.", ingredients: ["Cialda fritta con marsala", "Ricotta di pecora", "Zucchero", "Gocce di cioccolato o canditi"], funFact: "Gli abitanti arbëreshë di Piana custodiscono gelosamente la ricetta della scorza spessa e bollosa.", icon: "🥠" },
  { id: "pasta-taianu", category: "Cefalù", name: "Pasta a taianu", region: "Cefalù (PA)", description: "Scenografico timballo di rigatoni cotto in un tegame di terracotta (taianu), con strati di carne sfilacciata, melanzane fritte, pecorino e sugo.", ingredients: ["Rigatoni", "Carne di vitello e agnello", "Melanzane fritte", "Pecorino", "Estratto di pomodoro"], funFact: "Preparato tradizionalmente per la festa patronale del SS. Salvatore tra i carboni ardenti.", icon: "🍲" },
  { id: "pane-monreale", category: "Monreale", name: "Pane di Monreale", region: "Monreale (PA)", description: "Grande pagnotta di grano duro cotta nei forni a legna, con crosta croccante e dorata e mollica morbida e alveolata.", ingredients: ["Farina di grano duro siciliano", "Lievito madre", "Acqua e Sale"], funFact: "Conserva la freschezza per diversi giorni grazie alla qualità superiore delle farine locali.", icon: "🍞" },
  { id: "biscotti-s", category: "Monreale", name: 'Biscotti a "S"', region: "Monreale (PA)", description: 'Tipici biscotti secchi aromatizzati con semi di anice, modellati a forma della lettera "S", perfetti da inzuppare nel vino liquoroso.', ingredients: ["Farina", "Zucchero", "Strutto", "Semi o essenza di anice", "Uova"], funFact: "Sono il souvenir gastronomico immancabile per chi visita il maestoso Duomo di Monreale.", icon: "🍪" },
  { id: "manna-madonie", category: "Castelbuono", name: "Manna delle Madonie", region: "Castelbuono (PA)", description: "Preziosa e dolce linfa naturale estratta dai fusti dei frassini delle Madonie mediante incisioni praticate d'estate.", ingredients: ["Linfa naturale di frassino (Manna pura)"], funFact: "È un dolcificante naturale antichissimo, presidio Slow Food, noto per le proprietà digestive.", icon: "🌿" },
  { id: "caciocavallo-palermitano", category: "Cinisi / Madonie", name: "Caciocavallo Palermitano", region: "Cinisi / Madonie (PA)", description: "Storico formaggio a pasta filata a forma di sacchetto, prodotto con latte crudo della pregiata vacca Cinisara.", ingredients: ["Latte crudo di Vacca Cinisara", "Caglio", "Sale"], funFact: "Il latte della vacca Cinisara dona al formaggio sentori unici di erbe selvatiche di montagna.", icon: "🧀" },
  { id: "fagiolo-badda", category: "Polizzi Generosa", name: "Fagiolo Badda", region: "Polizzi Generosa (PA)", description: 'Rarissimo legume tondo (da cui "badda", palla) bicolore, dal sapore erbaceo e vellutato con note di castagna.', ingredients: ["Fagiolo Badda bianco e nero/rosato", "Aglio", "Finocchietto selvatico"], funFact: "Presidio Slow Food coltivato esclusivamente nell'area montana delle Madonie.", icon: "🫘" },
  { id: "carciofi-spinosi", category: "Termini Imerese", name: "Carciofi spinosi", region: "Termini Imerese (PA)", description: 'Pregiati carciofi locali dal gambo lungo e foglie violette ricche di spine, spesso cucinati "ammuddicati" (ripieni di mollica e formaggio).', ingredients: ["Carciofo spinoso di Termini", "Pangrattato", "Pecorino", "Aglio e Prezzemolo"], funFact: "Sono i protagonisti indiscussi delle tavole primaverili della provincia palermitana.", icon: "🥗" },
  { id: "froscia", category: "Termini Imerese", name: "Froscia", region: "Termini Imerese (PA)", description: "Ricca e soffice frittata tradizionale preparata con ricotta fresca, uova, pecorino, pezzetti di pane raffermo e finocchietto selvatico.", ingredients: ["Uova", "Ricotta fresca", "Pecorino", "Pane raffermo", "Finocchietto selvatico"], funFact: "Nasce come piatto di recupero contadino ma è diventata una vera prelibatezza locale.", icon: "🍳" },
  { id: "cous-cous-trapanese", category: "Trapani", name: "Cous cous alla trapanese", region: "Trapani", description: "Straordinario cous cous di semola incocciata a mano, cotto nella couscoussera tradizionale e bagnato con una ricca zuppa di pesce di scoglio.", ingredients: ["Semola incocciata", "Zuppa di pesce di scoglio", "Aglio rosso", "Cipolla", "Olio e Mandorle"], funFact: 'Celebra l\'integrazione mediterranea ed è al centro del famoso "Cous Cous Fest".', icon: "🍲" },
  { id: "busiate-pesto", category: "Trapani", name: "Busiate al pesto trapanese", region: "Trapani", description: "Pasta fresca a spirale condita con un pesto crudo pestato nel mortaio a base di pomodoro, aglio rosso di Nubia, mandorle e basilico.", ingredients: ["Busiate (pasta fresca)", "Pomodori freschi", "Aglio rosso", "Mandorle pelate", "Basilico", "Pecorino"], funFact: 'Il nome della pasta deriva dalla "busa", il fusto d\'erba usato per arrotolare l\'impasto.', icon: "🍝" },
  { id: "pizza-rianata", category: "Trapani", name: "Pizza Rianata", region: "Trapani", description: "Rustica e profumatissima pizza trapanese condita con pomodoro, acciughe, aglio, pecorino e una pioggia abbondante di origano (rianu).", ingredients: ["Impasto rustico", "Pomodori pelati", "Acciughe", "Aglio", "Pecorino", "Origano abbondante"], funFact: 'Il nome "rianata" deriva proprio dall\'uso massiccio e caratteristico dell\'origano locale.', icon: "🍕" },
  { id: "cabucio", category: "Trapani", name: "Cabucio", region: "Trapani", description: "Morbida focaccina ottenuta con l'impasto della pizza, farcita tradizionalmente con pomodoro, olio, acciughe, sale, pepe e origano.", ingredients: ["Impasto da pizza", "Pomodoro fresco", "Acciughe", "Olio extravergine", "Origano"], funFact: "Nato nei forni di Erice e Trapani, è lo street food perfetto da mangiare passeggiando.", icon: "🥪" },
  { id: "graffe-trapanesi", category: "Trapani", name: "Graffe Trapanesi", region: "Trapani", description: "Sofficissime ciambelle di pasta lievitata fritta, farcite generosamente con crema di ricotta di pecora e ricoperte di zucchero semolato.", ingredients: ["Pasta brioche fritta", "Crema di ricotta di pecora", "Zucchero semolato"], funFact: "Da non confondere con le graffe napoletane: qui il ripieno di ricotta fresca la fa da padrone.", icon: "🍩" },
  { id: "ghiotta", category: "Trapani", name: "Ghiotta (Zuppa di pesce)", region: "Trapani", description: "Denso e saporito intingolo marinaro a base di pesci da scoglio, pomodoro, aglio, mandorle tostate e prezzemolo.", ingredients: ["Pesci di scoglio", "Pomodoro", "Aglio", "Mandorle", "Prezzemolo"], funFact: "Viene usata sia come zuppa di pesce sia per condire la pasta o accompagnare il cous cous.", icon: "🥣" },
  { id: "genovesi-ericine", category: "Erice", name: "Genovesi ericine", region: "Erice (TP)", description: "Dolci di pasta frolla burrosa serviti tiepidi, ripieni di delicata crema pasticcera e spolverati di zucchero a velo.", ingredients: ["Pasta frolla", "Crema pasticcera al limone", "Zucchero a velo"], funFact: "La tradizione vuole che vadano gustate calde appena sfornate tra le viuzze medievali di Erice.", icon: "🥟" },
  { id: "mustaccioli", category: "Erice", name: "Mustaccioli", region: "Erice (TP)", description: "Antichi biscotti speziati preparati nei conventi ericini, duri e aromatici, profumati con miele e spezie.", ingredients: ["Farina", "Miele cotto", "Cannella", "Chiodi di garofano", "Sesamo"], funFact: "Venivano marchiati con appositi stampi in legno intagliati dalle monache di clausura.", icon: "🍪" },
  { id: "gambero-rosso", category: "Mazara del Vallo", name: "Gambero Rosso di Mazara", region: "Mazara del Vallo (TP)", description: "L'oro del Mediterraneo: crostaceo dal colore corallo brillante e dalla polpa incredibilmente dolce e morbida.", ingredients: ["Gambero Rosso fresco (Aristaeomorpha foliacea)"], funFact: "I puristi lo consumano rigorosamente crudo, senza limone, per apprezzarne la dolcezza unica.", icon: "🦐" },
  { id: "caldo-freddo", category: "San Vito Lo Capo", name: "Caldo Freddo", region: "San Vito Lo Capo (TP)", description: "Irresistibile dolce al cucchiaio con pan di spagna imbevuto di liquorino, gelato artigianale, panna e una colata di cioccolato fondente caldo.", ingredients: ["Pan di spagna", "Liquore", "Gelato artigianale", "Panna montata", "Cioccolato fondente caldo"], funFact: "Il contrasto termico tra cioccolato caldo e gelato freddo crea un'esperienza unica.", icon: "🍨" },
  { id: "cannolo-dattilo", category: "Dattilo / Paceco", name: "Cannolo di Dattilo", region: "Dattilo / Paceco (TP)", description: "Cannolo famoso per le dimensioni extra-large e per la ricotta di pecora lavorata in modo rustico e cremoso.", ingredients: ["Cialda croccante", "Ricotta di pecora grezza", "Zucchero", "Cioccolato"], funFact: "I bar di Dattilo sono una meta di pellegrinaggio obbligatoria per i golosi di tutta la regione.", icon: "🥠" },
  { id: "aglio-rosso-nubia", category: "Dattilo / Paceco", name: "Aglio Rosso di Nubia", region: "Paceco / Nubia (TP)", description: "Pregiato aglio dalle tuniche esterne di colore rosso porpora intenso, dal gusto deciso ma gradevole.", ingredients: ["Aglio Rosso di Nubia (Presidio Slow Food)"], funFact: 'Viene intrecciato a mano in caratteristiche "trizze" (trecce) appese nelle case tradizionali.', icon: "🧄" },
  { id: "pane-nero-castelvetrano", category: "Castelvetrano", name: "Pane Nero di Castelvetrano", region: "Castelvetrano (TP)", description: "Pane scuro cotto a legna, impastato con farina di grano antico Tumminia e semola, dalla crosta cosparsa di semi di sesamo.", ingredients: ["Farina di Tumminia", "Semola di grano duro", "Lievito madre", "Semi di sesamo"], funFact: "Il colore scuro e il profumo tostato derivano dalle caratteristiche uniche del grano Tumminia.", icon: "🍞" },
  { id: "olive-nocellara", category: "Castelvetrano", name: "Olive Nocellara del Belìce", region: "Castelvetrano (TP)", description: "Polpose olive verdi tonde DOP, croccanti e dal sapore burroso con retrogusto leggermente piccante.", ingredients: ["Olive Nocellara del Belìce", "Acqua e Sale"], funFact: "Tra le poche olive al mondo a fregiarsi di due denominazioni DOP distinte (da tavola e per l'olio).", icon: "🫒" },
  { id: "pane-cunzato", category: "Scopello / Castellammare", name: "Pane cunzato", region: "Scopello (TP)", description: "Calda pagnotta di paese condita generosamente con olio extravergine, pomodoro, acciughe, formaggio primo sale, origano e pepe.", ingredients: ["Pagnotta casereccia calda", "Olio d'oliva", "Pomodoro", "Primo sale", "Acciughe", "Origano"], funFact: "Gustarlo affacciati sui faraglioni di Scopello è uno dei piaceri supremi dell'estate siciliana.", icon: "🥖" },
  { id: "cassatelle-ricotta", category: "Scopello / Castellammare", name: "Cassatelle (Cassateddi)", region: "Castellammare del Golfo (TP)", description: "Grandi ravioli di pasta dolce fritta, dorati e pieni di bolle, ripieni di vellutata crema di ricotta di pecora e gocce di cioccolato.", ingredients: ["Pasta frolla fritta", "Ricotta di pecora zuccherata", "Cioccolato fondente", "Zucchero a velo"], funFact: "Si mangiano rigorosamente calde, spolverate di zucchero a velo e cannella.", icon: "🥟" },
  { id: "vastedda-belice", category: "Valle del Belìce", name: "Vastedda della Valle del Belìce DOP", region: "Valle del Belìce (TP)", description: "L'unico formaggio di pecora a pasta filata d'Italia. Ha una forma a focaccia e un gusto fresco, acidulo e burroso.", ingredients: ["Latte di pecora della Valle del Belìce", "Caglio", "Sale"], funFact: "Nacque quasi per errore recuperando una pasta cagliata difettosa filandola in acqua calda.", icon: "🧀" },
  { id: "capperi-pantelleria", category: "Pantelleria", name: "Capperi di Pantelleria IGP", region: "Pantelleria (TP)", description: "I capperi più famosi al mondo, raccolti sulle rocce vulcaniche dell'isola e conservati sotto sale marino grosso.", ingredients: ["Boccioli di cappero", "Sale marino IGP di Pantelleria"], funFact: "Grazie al suolo vulcanico sviluppano un profilo aromatico inconfondibile e persistente.", icon: "🌿" },
  { id: "insalata-pantesca", category: "Pantelleria", name: "Insalata Pantesca", region: "Pantelleria (TP)", description: "Fresca insalata estiva con patate lesse, pomodori freschi, cipolla rossa, capperi di Pantelleria, olive nere e origano.", ingredients: ["Patate", "Pomodori", "Cipolla", "Capperi IGP", "Olive", "Olio e Aceto"], funFact: "Spesso arricchita con pezzetti di formaggio locale tuma o tonno sott'olio.", icon: "🥗" },
  { id: "bacio-pantesco", category: "Pantelleria", name: "Bacio Pantesco", region: "Pantelleria (TP)", description: "Due sottili dischi di pastella fritta croccante legati insieme da un generoso ripieno di crema di ricotta dolce e gocce di cioccolato.", ingredients: ["Pastella croccante fritta", "Ricotta di pecora", "Zucchero", "Cioccolato fondente"], funFact: "Il nome evocativo richiama la dolcezza e la forma di questo dessert dell'isola nera.", icon: "💋" },
  { id: "pesto-pantesco", category: "Pantelleria", name: "Pesto Pantesco", region: "Pantelleria (TP)", description: "Intenso pesto a crudo preparato pestando pomodoro, aglio, basilico, olio, mandorle e immancabili capperi panteschi.", ingredients: ["Pomodori freschi", "Capperi di Pantelleria", "Aglio", "Basilico", "Olio d'oliva", "Mandorle"], funFact: "Ottimo condimento espresso per la pasta o spalmato su crostini di pane casereccio.", icon: "🫙" },
  { id: "vino-passito", category: "Pantelleria", name: "Vino Passito di Pantelleria", region: "Pantelleria (TP)", description: "Nettare dolce e dorato ottenuto da uve Zibibbo (Moscato di Alessandria) fatte appassire al sole sui terreni lavici.", ingredients: ["Uve Zibibbo passite al sole"], funFact: "La vite ad alberello di Pantelleria è Patrimonio Immateriale dell'UNESCO.", icon: "🍷" },
  { id: "tonno-rosso", category: "Isole Egadi (Favignana)", name: "Tonno rosso", region: "Favignana - Egadi (TP)", description: "Il pregiato re dei mari di Favignana, pescato secondo le secolari tecniche tradizionali delle tonnare.", ingredients: ["Tranci di Tonno Rosso fresco del Mediterraneo"], funFact: "Le Egadi sono storicamente il cuore pulsante della mattanza e della cultura del tonno.", icon: "🐟" },
  { id: "bottarga-tonno", category: "Isole Egadi (Favignana)", name: "Bottarga di tonno", region: "Favignana - Egadi (TP)", description: "Uova di tonno salate, pressate e stagionate pazientemente, dall'inconfondibile colore ambrato e sapore marino intenso.", ingredients: ["Uova di tonno", "Sale marino"], funFact: "Viene grattugiata finemente sulla pasta o tagliata a sottilissime scaglie come antipasto raffinato.", icon: "✨" },
  { id: "lattume", category: "Isole Egadi (Favignana)", name: "Lattume", region: "Favignana - Egadi (TP)", description: "Prelibatezza marinara costituita dalle gonadi maschili del tonno, solitamente infarinate e fritte o gustate ai ferri.", ingredients: ["Lattume di tonno fresco", "Farina di semola", "Olio per friggere"], funFact: "Considerato una vera rarità gastronomica per veri intenditori della cucina delle tonnare.", icon: "🍽️" },
  { id: "bresaola-tonno", category: "Isole Egadi (Favignana)", name: "Bresaola (Ficazza) di tonno", region: "Favignana - Egadi (TP)", description: "Salume di mare stagionato ottenuto dalla lavorazione e insaccatura delle parti magre del tonno rosso.", ingredients: ["Carne di tonno rosso", "Spezie", "Sale marino"], funFact: 'Conosciuta come "ficazza", si affetta sottilissima e si condisce con olio e limone.', icon: "🥩" },
  { id: "polpette-tonno", category: "Isole Egadi (Favignana)", name: "Polpette di tonno fresco", region: "Favignana - Egadi (TP)", description: "Morbide polpette casalinghe preparate con tonno fresco tritato, pane raffermo, capperi, prezzemolo, aglio e fritte o ripassate al sugo.", ingredients: ["Tonno fresco", "Pane raffermo", "Capperi", "Prezzemolo", "Uova"], funFact: "Un piatto povero ma ricchissimo di sapore che valorizza il pescato giornaliero.", icon: "🧆" },
  { id: "vino-marsala", category: "Marsala", name: "Vino Marsala", region: "Marsala (TP)", description: "Il leggendario vino liquoroso siciliano, famoso in tutto il mondo per le sue note calde, ambrate e complesse.", ingredients: ["Uve Grillo, Catarratto o Inzolia", "Mosto cotto e Alcol vinico"], funFact: "Fu commercializzato su scala globale nel Settecento dal mercante inglese John Woodhouse.", icon: "🍷" },
];

export const foodCategories = ["All", ...Array.from(new Set(culinaryData.map((d) => d.category)))];
